### PR TITLE
Add codeclimate markdown lint plugin

### PR DESCRIPTION
**Pull request by DanVanAtta**
Set up code climate config file with third party plugin to do
markdown linting.

### CODE REVIEW

**Comment by RoiEXLab** [comment]
Interesting, looks like https://github.com/triplea-game/triplea/issues/5608 indeed did have an impact.
I mean good thing it got caught

**Comment by DanVanAtta** [comment]
@RoiEXLab what was the impact? I've missed it so far.

**Comment by DanVanAtta** [comment]
@RoiEXLab ah, spotted it

**Comment by DanVanAtta** [comment]
I pushed the missing tags, with luck should all be okay now.

**Comment by DanVanAtta** [comment]
Actually, we'll need artifacts to be created, I'm not sure how well that is going to go : (

**Comment by DanVanAtta** [comment]
For follow-up, we may want to add eslint as well:

https://docs.codeclimate.com/docs/eslint 
```
 eslint:
    enabled: true
```

**Comment by RoiEXLab** [comment]
I guess this can be merged?

**Pull request merged**
