### PR TITLE
Dyn url deconflict

### PR DESCRIPTION
**Pull request by DanVanAtta**

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@DanVanAtta looks good

**Comment by ron-murhammer** [comment]
I merged #180. Is this needed as well?

**Comment by RoiEXLab** [comment]
Not anymore... 
This can be closed!

**Comment by RoiEXLab** [comment]
@ron-murhammer By the way...
The description of this repo says http:/ instead of http://
This should be fixed

**Comment by ron-murhammer** [comment]
Fixed the description and closed this.

**Pull request closed without merging**
