### PR TITLE
Add release notes for 1.9.0.0.12226

### PR DESCRIPTION
**Pull request by ssoloff**
Simply adds a placeholder for the 11996 release notes.  I did not go through all 547 PRs merged as part of this release to create an added/changed/fixed list.  Please feel free to push additional commits to this branch to add important PRs associated with this release.

**EDIT:** Now including 12226 since it was released while this PR was open.

### CODE REVIEW

**Comment by ssoloff** [comment]
@DanVanAtta @RoiEXLab @ron-murhammer Bumping...

**Comment by ron-murhammer** [comment]
@ssoloff Given that 11996 was the stable for such a short period of time, might be easier to just do 12226.

**Comment by ssoloff** [comment]
@ron-murhammer bb6193d

**Comment by ssoloff** [comment]
@ron-murhammer Based on your most recent comment, I was leaving this open because I wasn't sure if you wanted to push changes to this PR directly or make those changes in a follow-up.  If the latter, please merge at your convenience.  If the former, carry on. :smile:

**Comment by ron-murhammer** [comment]
@ssoloff Should be fine to post. If someone wants to add more then we can always put further updates.

**Pull request merged**
