### PR TITLE
Correct false statement that GPL is non-commercial

### PR DESCRIPTION
**Pull request by trevorld**
Not only does the GPL allow commercial use but in fact commercial use is one of the 4 basic freedoms that the GPL seeks to preserve (and forbidding commercial use means you can't be hosted in the Debian Linux repositories among other free software repositories).  Commercial distribution of GPL code is how Sourceforge makes money (i.e. showing ads).  However the fact that you must share the source code and allow others to freely give away your changes does make it hard to make money commercially from a Triple A fork...

https://www.gnu.org/licenses/gpl-faq.html#GPLCommercially

### CODE REVIEW

**Comment by ssoloff** [comment]
Agree with this.  I suspect there was some confusion between the terms _commercial_ and _proprietary_, the former being permitted as described by the OP, while the latter is explicitly prohibited.

However, I would suggest that we simply use some FSF boilerplate for this license instead of getting into the weeds about commercial usage.  Also, we probably want to update the text to make it clear that we're using GPL v2.  I'll offer up the standard GPL notice for consideration:

> TripleA is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. TripleA is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the [GNU General Public License](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html) for more details.

**Comment by trevorld** [comment]
I'm not sure if Triple A is GPL-2 or GPL-2+ but if it is the former the standard boilerplate notice should be:

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; **version 2.**  ~~either version 2 of the License, or (at your option) any later version.~~

**Comment by ssoloff** [comment]
FWIW, the original license text Sean added to the source in 2002 included the "any later version" clause (see [triplea-game/triplea@6b5a957](https://github.com/triplea-game/triplea/commit/6b5a957#diff-b4627b82acbc76c03e10ccd117567e6b)).  @ron-murhammer, @DanVanAtta, or @veqryn may know if this licensing option was ever removed.

**Comment by veqryn** [comment]
👍

**Comment by DanVanAtta** [comment]
This is a good correction, thank you!

**Pull request merged**
