### PR TITLE
Dynamic URL attempt 2

### PR DESCRIPTION
**Pull request by RoiEXLab**
#156 without any merges

### CODE REVIEW

**Comment by RoiEXLab** [comment]
@DanVanAtta I didn't Change anything, but I hope no merging issues are shown...

**Comment by DanVanAtta** [comment]
Sry to report:
bad_news

**Comment by RoiEXLab** [comment]
@DanVanAtta I merged the current master into this branch...
Awaiting your feedback

**Comment by RoiEXLab** [comment]
@DanVanAtta If this isn't working either, please feel free to create [this PR](https://github.com/triplea-game/triplea-game.github.io/compare/master...RoiEXLab:clean-dyn-url?expand=1) and merge it afterwards...
I recommited the changes in a single commit on a clean branch. This should definetely work, but I would get rid of all the individual commits

**Comment by theredbaronaaa** [comment]
@RoiEXLab FYI, with my new changes to the maps page, I'm bringing back scripts.js with about 40 more lines to handle all that I need just for the listing. In the end, this should be a large file, as JS will be key to coding a lot of the maps page functionality even beyond the listing.

Is it worth moving *all* the scripts to the footer in-line? I'd rather keep some things in their own file and just perhaps have function calls and the like in the footer, the bare minimum, though those are only my preferences. For long term maintenance, I've generally found that compartmentalization is better, though I'm no Javascript whiz 😛

I guess all I'm interested in is your reasoning, which could very well be perfectly sound. Let's just be doubly sure our changes are future proof.

**Comment by RoiEXLab** [comment]
@theredbaronaaa What you could do is creating a separate js file which is referenced in the footer.
This keeps everything clean, causes the script not to be loaded uneccessarily and won't conflict with my pending PR

**Comment by RoiEXLab** [comment]
The reason I removed the file is that it was references in every document although ut was only used on the download page

**Comment by theredbaronaaa** [comment]
Makes sense. The maps page JS is references across about 5 pages right now, so I'll keep that in mind 👍

**Comment by RoiEXLab** [comment]
@ron-murhammer just for reference: Is it telling you that there are conflicts as well?

**Comment by ron-murhammer** [comment]
@RoiEXLab Nope, its not showing any conflicts on this PR for me.

**Comment by RoiEXLab** [comment]
@ron-murhammer I believe @DanVanAtta agreed with this changes.
I'd really like to do some refactoring, but this will require this PR to be merged first in order to avoid any kind of conflict.

**Comment by theredbaronaaa** [comment]
@ron-murhammer @RoiEXLab Second that. In this post especially: https://github.com/triplea-game/triplea-game.github.io/pull/156#issuecomment-294095534. I've reviewed the code visually and also think that it can be merged. If I'm not mistaken, the only reason @DanVanAtta hasn't merged this himself is because of the conflicts.

**Comment by ron-murhammer** [comment]
@RoiEXLab @theredbaronaaa So this PR is primarily just making it so the website points to the latest release we tag in github instead of specifying a specific version correct? So it should reduce some extra steps when updating versions but we will need to be pretty aware that when we tag a release in github it goes live on the website?

**Comment by RoiEXLab** [comment]
Yes, but it only uses "full-releases", e.g. Pre-releases/common builds are ignored.

**Comment by RoiEXLab** [comment]
@ron-murhammer It basically keeps track of the release located at https://github.com/triplea-game/triplea/releases/latest which is the latest build not marked as pre-release

**Comment by RoiEXLab** [comment]
@DanVanAtta @ron-murhammer Would you please mind?

**Comment by DanVanAtta** [comment]
Still see a conflict. Checking out this branch I had to resolve conflicts in '__config.yml' when rebasing against master.

I opened this branch with those conflicts resolved. Please double check: https://github.com/triplea-game/triplea-game.github.io/pull/183

**Comment by RoiEXLab** [comment]
Thanks @ron-murhammer
This is the weirdest bug I ever experienced on github

**Pull request merged**
