### PR TITLE
Add source code download link

### PR DESCRIPTION
**Pull request by DanVanAtta**
Requested in: https://github.com/triplea-game/triplea/issues/1565

### CODE REVIEW

**Comment by RoiEXLab** [comment]
I added this to #156, since site.gameversion will no longer be available

**Comment by DanVanAtta** [comment]
@RoiEXLab  i'm getting an error with the link you provided. Please confirm.

**Comment by RoiEXLab** [comment]
Do you mean the link to the other PR? 
Or `site.gameversion`? Which is a field accrssible by liquid.

**Comment by DanVanAtta** [comment]
@RoiEXLab  if things aren't moving at a good clip in #156, let me know and we can resurrect this change. Will close in the meantime.

**Pull request closed without merging**
